#!/usr/bin/env python3
"""pidf.py — ESP-IDF-shaped CLI for pico-idf."""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

VERSION = "0.2.0"

TARGETS = {
    "pico_w": {"board": "pico_w", "platform": None, "wireless": True},
    "pico2_w": {"board": "pico2_w", "platform": None, "wireless": True},
    "pico2_w_riscv": {
        "board": "pico2_w",
        "platform": "rp2350-riscv",
        "wireless": True,
    },
    "pico": {"board": "pico", "platform": None, "wireless": False},
    "pico2": {"board": "pico2", "platform": None, "wireless": False},
}

DEFAULT_SDKCONFIG = """\
# Generated by pidf.py set-target. Edit with: pidf.py menuconfig
CONFIG_PIDF_TARGET="{target}"
CONFIG_PIDF_BOARD="{board}"
CONFIG_FREERTOS_SMP=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_BLINK_GPIO={blink_gpio}
"""

PREFERRED_FEATURES = ["nvs", "wifi", "esp_netif", "http-client", "mqtt", "ble", "uart"]
ALLOWED_FEATURE_STATUS = {"done", "partial", "planned", "impossible"}


def pidf_path() -> Path:
    env = os.environ.get("PIDF_PATH")
    if env:
        return Path(env).resolve()
    return Path(__file__).resolve().parent.parent


def project_dir() -> Path:
    env = os.environ.get("PIDF_PROJECT")
    if env:
        return Path(env).resolve()
    cwd = Path.cwd().resolve()
    marker = cwd / "CMakeLists.txt"
    if marker.exists() and "project.cmake" in marker.read_text(encoding="utf-8"):
        return cwd
    example = pidf_path() / "examples" / "get-started" / "blink"
    return example


def features_path() -> Path:
    return pidf_path() / "tools" / "features.json"


def load_features() -> dict:
    return json.loads(features_path().read_text(encoding="utf-8"))


def sdkconfig_path(proj: Path) -> Path:
    return proj / "sdkconfig"


def read_sdkconfig(proj: Path) -> dict[str, str]:
    cfg: dict[str, str] = {}
    path = sdkconfig_path(proj)
    if not path.exists():
        defaults = proj / "sdkconfig.defaults"
        path = defaults if defaults.exists() else path
    if not path.exists():
        return cfg
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("CONFIG_") and "=" in line:
            key, value = line.split("=", 1)
            cfg[key] = value.strip().strip('"')
    return cfg


def current_target(proj: Path) -> str:
    cfg = read_sdkconfig(proj)
    return cfg.get("CONFIG_PIDF_TARGET", "pico_w")


def write_target(proj: Path, target: str) -> Path:
    if target not in TARGETS:
        raise ValueError(f"unknown target {target!r}; choose from: {', '.join(TARGETS)}")
    spec = TARGETS[target]
    blink = "32" if spec["wireless"] else "25"
    path = sdkconfig_path(proj)
    path.write_text(
        DEFAULT_SDKCONFIG.format(target=target, board=spec["board"], blink_gpio=blink),
        encoding="utf-8",
    )
    return path


def set_sdkconfig_value(proj: Path, key: str, value: str) -> Path:
    path = sdkconfig_path(proj)
    if not path.exists():
        write_target(proj, current_target(proj))
    if not key.startswith("CONFIG_"):
        key = "CONFIG_" + key
    lines = path.read_text(encoding="utf-8").splitlines() if path.exists() else []
    replaced = False
    out = []
    for line in lines:
        if line.startswith(key + "="):
            out.append(f"{key}={value}")
            replaced = True
        else:
            out.append(line)
    if not replaced:
        out.append(f"{key}={value}")
    path.write_text("\n".join(out) + "\n", encoding="utf-8")
    return path


def run_build(proj: Path, fresh: bool = False, jobs: int | None = None) -> tuple[int, str]:
    bdir = build_dir(proj)
    if fresh:
        shutil.rmtree(bdir, ignore_errors=True)
    bdir.mkdir(parents=True, exist_ok=True)
    cmake = ["cmake", "-S", str(proj), "-B", str(bdir), *cmake_args(proj)]
    log: list[str] = ["+ " + " ".join(cmake)]
    proc = subprocess.run(cmake, text=True, capture_output=True, check=False)
    log.append(proc.stdout)
    log.append(proc.stderr)
    if proc.returncode != 0:
        return proc.returncode, "\n".join(log)
    njob = jobs or os.cpu_count() or 2
    build = ["cmake", "--build", str(bdir), "-j", str(njob)]
    log.append("+ " + " ".join(build))
    proc = subprocess.run(build, text=True, capture_output=True, check=False)
    log.append(proc.stdout)
    log.append(proc.stderr)
    return proc.returncode, "\n".join(log)


def feature_by_id(feature_id: str) -> dict:
    data = load_features()
    for row in data["features"]:
        if row["id"] == feature_id:
            return row
    raise KeyError(feature_id)


def planned_features() -> list[dict]:
    planned = [r for r in load_features()["features"] if r["status"] == "planned"]
    planned.sort(
        key=lambda r: (
            PREFERRED_FEATURES.index(r["id"]) if r["id"] in PREFERRED_FEATURES else 100,
            r["id"],
        )
    )
    return planned


def next_planned_feature(feature_id: str | None = None) -> dict:
    if feature_id:
        return feature_by_id(feature_id)
    planned = planned_features()
    if not planned:
        raise KeyError("no planned features left")
    return planned[0]


def feature_implement_prompt(feature: dict) -> str:
    names = (
        "Public headers use the claw_* APIs in docs/CLAW.md (inspired names, original code)."
        if feature.get("group") == "claw"
        else "Public headers use the ESP-IDF names listed above."
    )
    return (
        f"Implement pico-idf feature `{feature['id']}` ({feature['title']}).\n\n"
        f"ESP-IDF API: {feature['esp_idf']}\n"
        f"Pico backend: {feature['backend']}\n"
        f"Current status: {feature['status']}\n"
        f"Notes: {feature.get('notes') or '(none)'}\n\n"
        "Follow AGENTS.md and docs/VIBECODING.md:\n"
        "- Clean-room implementation (do not copy ESP-IDF or ESP-Claw sources).\n"
        f"- {names}\n"
        "- Add examples/<group>/<id>/ that starts from app_main.\n"
        "- Host-test portable logic; cross-compile for pico_w and pico2_w.\n"
        "- Update tools/features.json status to done or partial.\n"
        "- Leave impossible rows impossible.\n"
    )


def update_feature_status(feature_id: str, status: str) -> dict:
    if status not in ALLOWED_FEATURE_STATUS:
        raise ValueError(f"status must be one of {sorted(ALLOWED_FEATURE_STATUS)}")
    data = load_features()
    found = None
    for row in data["features"]:
        if row["id"] == feature_id:
            found = row
            break
    if found is None:
        raise KeyError(feature_id)
    if found["status"] == "impossible" and status == "done":
        raise ValueError(
            f"{feature_id} is impossible on Pico hardware; "
            f"do not mark it done. {found.get('notes') or ''}"
        )
    found["status"] = status
    features_path().write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
    return found


def cmd_version(_: argparse.Namespace) -> int:
    print(f"pidf.py {VERSION}")
    print(f"PIDF_PATH={pidf_path()}")
    return 0


def cmd_set_target(args: argparse.Namespace) -> int:
    try:
        path = write_target(project_dir(), args.target)
    except ValueError as exc:
        print(str(exc), file=sys.stderr)
        return 2
    spec = TARGETS[args.target]
    print(f"Target set to {args.target} (PICO_BOARD={spec['board']}) in {path}")
    return 0


def cmake_args(proj: Path) -> list[str]:
    target = current_target(proj)
    spec = TARGETS.get(target, TARGETS["pico_w"])
    args = [
        f"-DPIDF_PATH={pidf_path()}",
        f"-DPICO_BOARD={spec['board']}",
        f"-DPIDF_TARGET={target}",
    ]
    if spec["platform"]:
        args.append(f"-DPICO_PLATFORM={spec['platform']}")
    sdk = os.environ.get("PICO_SDK_PATH")
    if sdk:
        args.append(f"-DPICO_SDK_PATH={sdk}")
    fr = os.environ.get("FREERTOS_KERNEL_PATH")
    if fr:
        args.append(f"-DFREERTOS_KERNEL_PATH={fr}")
    return args


def build_dir(proj: Path) -> Path:
    return proj / "build"


def cmd_build(args: argparse.Namespace) -> int:
    rc, log = run_build(project_dir(), fresh=args.fresh, jobs=args.jobs)
    print(log)
    return rc


def find_uf2(proj: Path) -> Path | None:
    matches = sorted(build_dir(proj).rglob("*.uf2"))
    return matches[0] if matches else None


def cmd_flash(args: argparse.Namespace) -> int:
    proj = project_dir()
    uf2 = find_uf2(proj)
    if uf2 is None:
        print("no .uf2 found; run pidf.py build first", file=sys.stderr)
        return 1
    picotool = shutil.which("picotool")
    if picotool and not args.uf2_only:
        cmd = [picotool, "load", "-x", str(uf2)]
        print("+", " ".join(cmd))
        return subprocess.call(cmd)
    dest = Path(args.mount or "/media/RPI-RP2")
    if dest.exists():
        print(f"copy {uf2} -> {dest}")
        shutil.copy2(uf2, dest)
        return 0
    print(f"built {uf2}")
    print("Hold BOOTSEL, mount the Pico, then re-run with --mount PATH")
    print("or install picotool and connect the board.")
    return 1


def cmd_monitor(args: argparse.Namespace) -> int:
    port = args.port or os.environ.get("PIDF_MONITOR_PORT", "/dev/ttyACM0")
    baud = str(args.baud)
    for tool in ("minicom", "screen", "picocom"):
        if shutil.which(tool):
            if tool == "minicom":
                cmd = [tool, "-D", port, "-b", baud]
            elif tool == "picocom":
                cmd = [tool, "-b", baud, port]
            else:
                cmd = [tool, port, baud]
            print("+", " ".join(cmd))
            return subprocess.call(cmd)
    print(f"open {port} at {baud} baud (install minicom, picocom, or screen)", file=sys.stderr)
    return 1


def cmd_menuconfig(args: argparse.Namespace) -> int:
    proj = project_dir()
    if args.set:
        key, _, value = args.set.partition("=")
        set_sdkconfig_value(proj, key, value)
        if not key.startswith("CONFIG_"):
            key = "CONFIG_" + key
        print(f"set {key}={value}")
        return 0
    path = sdkconfig_path(proj)
    if not path.exists():
        write_target(proj, current_target(proj))
    print(path.read_text(encoding="utf-8"))
    print("# pidf.py menuconfig --set KEY=value   (full TUI is planned)")
    return 0


def cmd_create_project(args: argparse.Namespace) -> int:
    dest = Path(args.path).resolve()
    dest.mkdir(parents=True, exist_ok=True)
    (dest / "main").mkdir(exist_ok=True)
    (dest / "CMakeLists.txt").write_text(
        "cmake_minimum_required(VERSION 3.13)\n"
        "include($ENV{PIDF_PATH}/tools/cmake/project.cmake)\n"
        f"project({dest.name})\n",
        encoding="utf-8",
    )
    (dest / "main" / "CMakeLists.txt").write_text(
        "idf_component_register(SRCS \"main.c\" INCLUDE_DIRS \".\")\n",
        encoding="utf-8",
    )
    (dest / "main" / "main.c").write_text(
        '#include "esp_log.h"\n\n'
        "static const char *TAG = \"app\";\n\n"
        "void app_main(void)\n"
        "{\n"
        '    ESP_LOGI(TAG, "hello from pico-idf");\n'
        "}\n",
        encoding="utf-8",
    )
    (dest / "sdkconfig.defaults").write_text(
        'CONFIG_PIDF_TARGET="pico_w"\nCONFIG_FREERTOS_SMP=y\n',
        encoding="utf-8",
    )
    print(f"created project {dest}")
    return 0


def cmd_create_component(args: argparse.Namespace) -> int:
    dest = pidf_path() / "components" / args.name
    dest.mkdir(parents=True, exist_ok=True)
    (dest / "include").mkdir(exist_ok=True)
    (dest / "CMakeLists.txt").write_text(
        f"idf_component_register(SRCS \"{args.name}.c\" INCLUDE_DIRS \"include\")\n",
        encoding="utf-8",
    )
    (dest / f"{args.name}.c").write_text(
        f'#include "{args.name}.h"\n',
        encoding="utf-8",
    )
    (dest / "include" / f"{args.name}.h").write_text(
        "#pragma once\n#include \"esp_err.h\"\n",
        encoding="utf-8",
    )
    print(f"created component {dest}")
    return 0


def _status_sort(item: dict) -> tuple:
    order = {"done": 0, "partial": 1, "planned": 2, "impossible": 3}
    return (order.get(item["status"], 9), item["group"], item["id"])


def cmd_vibe_status(args: argparse.Namespace) -> int:
    data = load_features()
    rows = data["features"]
    if args.status:
        rows = [r for r in rows if r["status"] == args.status]
    counts: dict[str, int] = {}
    for r in data["features"]:
        counts[r["status"]] = counts.get(r["status"], 0) + 1
    print(
        "pico-idf features: "
        + ", ".join(f"{k}={v}" for k, v in sorted(counts.items()))
    )
    print(f"{'id':<16} {'status':<12} {'group':<14} title")
    print("-" * 72)
    for r in sorted(rows, key=_status_sort):
        print(f"{r['id']:<16} {r['status']:<12} {r['group']:<14} {r['title']}")
        if args.verbose and r.get("notes"):
            print(f"                 {r['notes']}")
    return 0


def cmd_vibe_next(args: argparse.Namespace) -> int:
    try:
        feature = next_planned_feature(args.id)
    except KeyError as exc:
        print(str(exc), file=sys.stderr)
        return 2 if args.id else 0
    print(feature_implement_prompt(feature))
    return 0


def cmd_mcp(_: argparse.Namespace) -> int:
    from pidf_mcp import serve

    return serve()


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="pidf.py",
        description="ESP-IDF-shaped CLI for Raspberry Pi Pico W / Pico 2 W",
    )
    p.add_argument("-C", "--project", help="project directory (default: cwd or blink example)")
    sub = p.add_subparsers(dest="cmd", required=True)

    s = sub.add_parser("version", help="print version")
    s.set_defaults(func=cmd_version)

    s = sub.add_parser("set-target", help="select pico_w / pico2_w / pico2_w_riscv / pico / pico2")
    s.add_argument("target", choices=sorted(TARGETS))
    s.set_defaults(func=cmd_set_target)

    s = sub.add_parser("build", help="configure and build the current project")
    s.add_argument("-j", "--jobs", type=int, default=None)
    s.add_argument("--fresh", action="store_true", help="wipe the build directory first")
    s.set_defaults(func=cmd_build)

    s = sub.add_parser("flash", help="load firmware with picotool or UF2 copy")
    s.add_argument("--mount", help="UF2 mass-storage mount point")
    s.add_argument("--uf2-only", action="store_true")
    s.set_defaults(func=cmd_flash)

    s = sub.add_parser("monitor", help="open the USB serial console")
    s.add_argument("-p", "--port", default=None)
    s.add_argument("-b", "--baud", type=int, default=115200)
    s.set_defaults(func=cmd_monitor)

    s = sub.add_parser("menuconfig", help="show or set sdkconfig values")
    s.add_argument("--set", help="KEY=value")
    s.set_defaults(func=cmd_menuconfig)

    s = sub.add_parser("create-project", help="create an app_main project")
    s.add_argument("path")
    s.set_defaults(func=cmd_create_project)

    s = sub.add_parser("create-component", help="create a components/ skeleton")
    s.add_argument("name")
    s.set_defaults(func=cmd_create_component)

    s = sub.add_parser("vibe", help="vibe-coding helpers")
    vs = s.add_subparsers(dest="vibe_cmd", required=True)
    st = vs.add_parser("status", help="print the feature matrix")
    st.add_argument("--status", choices=["done", "partial", "planned", "impossible"])
    st.add_argument("-v", "--verbose", action="store_true")
    st.set_defaults(func=cmd_vibe_status)
    nxt = vs.add_parser("next", help="print the agent prompt for the next planned feature")
    nxt.add_argument("id", nargs="?")
    nxt.set_defaults(func=cmd_vibe_next)

    s = sub.add_parser("mcp", help="run the pico-idf MCP server on stdio")
    s.set_defaults(func=cmd_mcp)

    return p


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    if getattr(args, "project", None):
        os.environ["PIDF_PROJECT"] = str(Path(args.project).resolve())
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
